# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: a1416

on:
  #schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    #- cron : '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write

jobs:
  build:

    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Run python code
      run: |
        python abcd/py/a1416.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}
    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    - name: push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -a -m "updated logs" --allow-empty
        git push --force origin main  # **强制推送**
