name: a3012

on:
  #schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    #- cron : '0 * * * *'
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python abcd/py/a3012.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions Bot"

    - name: Commit changes
      run: |
        git add -A
        git diff --cached --quiet || git commit -m "Updated logs"

    - name: Pull latest changes (rebase)
      run: |
        git pull --rebase https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/lighttime176/priresc.git main

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/lighttime176/priresc.git main
