name: a3012

on:
  #schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    #- cron : '0 * * * *'
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python abcd/py/a3012.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}
    - name: Create logs directory
      run: |
        if (!(Test-Path "logs")) {
          New-Item -ItemType Directory -Path "logs"
        }
    - name: Collect workflow logs
      run: |
        Get-Content $env:GITHUB_WORKSPACE\abcd\py\3012.log | Out-File -FilePath logs/3012.log -Encoding utf8
      continue-on-error: true  # 避免日志文件不存在时出错

    - name: Upload logs as artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/3012.log

    - name: Commit and push logs to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add logs/3012.log
        git commit -m "Save workflow logs"
        git push
      continue-on-error: true  # 避免 push 失败时报错
