name: a5968

on:
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create logs directory
      run: |
        if (!(Test-Path "logs")) {
          New-Item -ItemType Directory -Path "logs"
        }

    - name: Run Python script
      run: python abcd/py/a5968.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}

    - name: Wait for log file
      run: Start-Sleep -Seconds 5

    - name: Debug logs
      run: |
        Get-ChildItem -Path logs -Recurse
        if (Test-Path logs/a5968.log) {
          Get-Content logs/a5968.log
        } else {
          echo "Log file not found."
        }

    - name: Upload logs as artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/a5968.log

    - name: Commit and push logs to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add logs/a5968.log
        git commit -m "Save workflow logs"
        git push
      continue-on-error: true
